server:
  port: 8881
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xander?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
#  rabbitmq: #rabbitmq相关配置
#    host: 127.0.0.1
#    port: 5672
#    username: cloudDev
#    password: cloudDev
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
redis:
  database: xander
  key:
    seckill:
      end: 'seckill:end' # 秒杀结束标志
      num: 'seckill:num' # 秒杀成功数量
      limit: 'seckill:limit' # 秒杀限购数量
      path: 'seckill:path' # 秒杀路径
      pathVerify: false #是否开启路径校验（测试时关闭）
    authCode: 'ums:authCode' # 验证码
    orderId: 'oms:orderId' # 订单Redis自增
    member: 'ums:member' # 会员信息缓存
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时
    seckill: 43200 # 12小时
logging:
  level:
    root: info
    com.macro.xander: debug